### ISSUE TITLE
memex ./app_setup.sh run problem

### ISSUE THREAD

**Issue by ruba912** [memex-explorer/memex-explorer#769]
Hi here is the problem when i run  ./app_setup.sh
Please help in this issue.
   from common_settings import *
  File "/home/explorer/memex-explorer/source/memex/common_settings.py", line 67, in <module>
    "base.views.project_context_processor",
TypeError: can only concatenate list (not "tuple") to list
./app_setup.sh: line 15: deactivate: No such file or directory

**Comment by brittainhard** [comment]
Can you give me some info in your system and python version?

**Comment by ruba912** [comment]
sure. i am using ubuntu 14.04 and python version 2.7

**Comment by ruba912** [comment]
Setting enable stream viz to: FalseTraceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/root/miniconda2/envs/memex/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/root/miniconda2/envs/memex/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/root/miniconda2/envs/memex/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/miniconda2/envs/memex/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/root/miniconda2/envs/memex/lib/python2.7/site-packages/debug_toolbar/apps.py", line 15, in ready
    dt_settings.patch_all()
  File "/root/miniconda2/envs/memex/lib/python2.7/site-packages/debug_toolbar/settings.py", line 228, in patch_all
    patch_root_urlconf()
  File "/root/miniconda2/envs/memex/lib/python2.7/site-packages/debug_toolbar/settings.py", line 216, in patch_root_urlconf
    reverse('djdt:render_panel')
  File "/root/miniconda2/envs/memex/lib/python2.7/site-packages/django/core/urlresolvers.py", line 522, in reverse
    app_list = resolver.app_dict[ns]
  File "/root/miniconda2/envs/memex/lib/python2.7/site-packages/django/core/urlresolvers.py", line 329, in app_dict
    self._populate()
  File "/root/miniconda2/envs/memex/lib/python2.7/site-packages/django/core/urlresolvers.py", line 269, in _populate
    for pattern in reversed(self.url_patterns):
  File "/root/miniconda2/envs/memex/lib/python2.7/site-packages/django/core/urlresolvers.py", line 372, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/root/miniconda2/envs/memex/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/root/miniconda2/envs/memex/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ruba/memex-explorer/source/memex/urls.py", line 4, in <module>
    from rest import router, DataWakeView
  File "/home/ruba/memex-explorer/source/memex/rest.py", line 4, in <module>
    from rest_framework import routers, serializers, viewsets, parsers, filters
  File "/root/miniconda2/envs/memex/lib/python2.7/site-packages/rest_framework/routers.py", line 25, in <module>
    from rest_framework import views
  File "/root/miniconda2/envs/memex/lib/python2.7/site-packages/rest_framework/views.py", line 16, in <module>
    from rest_framework import exceptions, status
  File "/root/miniconda2/envs/memex/lib/python2.7/site-packages/rest_framework/exceptions.py", line 17, in <module>
    from rest_framework.utils.serializer_helpers import ReturnDict, ReturnList
  File "/root/miniconda2/envs/memex/lib/python2.7/site-packages/rest_framework/utils/serializer_helpers.py", line 8, in <module>
    from rest_framework.compat import unicode_to_repr
  File "/root/miniconda2/envs/memex/lib/python2.7/site-packages/rest_framework/compat.py", line 77, in <module>
    import django_filters
  File "/root/miniconda2/envs/memex/lib/python2.7/site-packages/django_filters/__init__.py", line 3, in <module>
    from .filterset import FilterSet
  File "/root/miniconda2/envs/memex/lib/python2.7/site-packages/django_filters/filterset.py", line 19, in <module>
    from .filters import (Filter, CharFilter, BooleanFilter,
  File "/root/miniconda2/envs/memex/lib/python2.7/site-packages/django_filters/filters.py", line 118, in <module>
    class UUIDFilter(Filter):
  File "/root/miniconda2/envs/memex/lib/python2.7/site-packages/django_filters/filters.py", line 119, in UUIDFilter
    field_class = forms.UUIDField
AttributeError: 'module' object has no attribute 'UUIDField'
discarding /root/miniconda2/envs/memex/bin from PATH

**Comment by lucastx** [comment]
Hello,

I was having the exact same problem. First time installing Memex-explorer.

I managed to fix this (and pass all tests) by freezing django-filter's version on ``environment.yml`` to 0.10:

```diff
diff --git a/environment.yml b/environment.yml
index 7fdc6fe..8a8ddeb 100644
--- a/environment.yml
+++ b/environment.yml
@@ -40,4 +40,4 @@ dependencies:
         - elasticsearch
         - supervisor
         - djangorestframework
-        - django-filter
+        - django-filter==0.10
```

Apparently newer versions of django-filters do not work with django 1.7.3 (which is also fixed at ``environment.yml``)

**Comment by britthard** [comment]
Support and development for this project has been suspended. We appreciate the help in clearing up these issues, and they will be solved when development is resumed.

Thanks.
